version: '3.8'

services:
  drupal:
    image: drupal:10
    ports:
      - "8080:80"
    environment:
      DRUPAL_SITE_NAME: "My Drupal Site"
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupaluser
      DRUPAL_DB_PASSWORD: drupalpass
    volumes:
      - drupal_data:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupaluser
      MYSQL_PASSWORD: drupalpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  drupal_data:
  db_data:
